---

#ansible-playbook -v --become -i hosts.ini --timeout 30 config-cluster-playbook.yml

- hosts: localhost
  gather_facts: false
  tasks:
    - name: "Check ansible version !=2.7.0"
      assert:
        msg: "Ansible V2.7.0 can't be used until: https://github.com/ansible/ansible/issues/46600 is fixed"
        that:
          - ansible_version.string is version("2.7.0", "!=")
          - ansible_version.string is version("2.6.0", ">=")
      tags:
        - check
  vars:
    ansible_connection: local

- hosts: bastion[0]
  gather_facts: False
  roles:
    - { role: kubespray-defaults}
    - { role: bastion-ssh-config, tags: ["localhost", "bastion"]}

- hosts: k8s-cluster
  name: Global k8s-cluster node configuration tasks
  become: yes
  gather_facts: true
  roles:
    - { role: kubespray-defaults}
  tasks:
    - include_tasks: tasks/k8s-cluster.yml

- hosts: kube-master
  name: Global k8s-master node configuration tasks
  become: yes
  gather_facts: true
  roles:
    - { role: kubespray-defaults}
  tasks:
    - include_tasks: tasks/k8s-master.yml

- hosts: kube-node
  name: Global k8s-node node configuration tasks
  become: yes
  gather_facts: true
  strategy: free
  vars:
    # storage can be `ceph` to deploy ceph on the ephemeral volumes
    # or `local` to deploy the local provisioner
    # Set the storage variable in the task below as well.
    - storage: "ceph"
    - n_local_volumes: 10
  roles:
    - { role: kubespray-defaults}
  tasks:
    - include_tasks: tasks/local-provisioner-node.yml
      when: storage == "local"
    - include_tasks: tasks/ceph-node.yml
      when: storage == "ceph"

- hosts: kube-master[0]
  tags:
    - k8sconf
  name: k8s deployment configuration tasks
  become: yes
  gather_facts: false
  vars:
    # See previus task for the `storage` variable
    storage: "ceph"
    helm:
      version: v2.13.1
      checksum: "sha256:c1967c1dfcd6c921694b80ededdb9bd1beb27cb076864e58957b1568bc98925a"
    local_provisioner:
      version: v2.3.0
      checksum: "sha256:d299b30e3c0728ab699acc10f42e4f16d9e5cb8c7395cfc006f9e4ee01c0c563"
    nfs_provisioner:
      version: 0.2.1
    jic_cluster:
      net: "172.30.4.0/23"
  roles:
    - { role: kubespray-defaults}
  tasks:
    - include_tasks: tasks/k8s-deployment-config.yml
    - include_tasks: tasks/k8s-deployment-config-local-provisioner.yml
      when: storage == "local"
    - include_tasks: tasks/k8s-deployment-config-ceph.yml
      when: storage == "ceph"

